Update Minecraft to 1.19
Also update Java version as new jar seems to require recent one.

Error: LinkageError occurred while loading main class net.minecraft.bundler.Main
        java.lang.UnsupportedClassVersionError: net/minecraft/bundler/Main has been compiled by 
        a more recent version of the Java Runtime (class file version 61.0), this version of the
        Java Runtime only recognizes class file versions up to 55.0